version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: datastream
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  microb:
    build: ./services/microB
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASS=
    depends_on:
      mysql:
        condition: service_healthy

  microa:
    build: ./services/microA
    ports:
      - "8090:8090"
    environment:
      - MICROB_ADDR=microb:50051
      - SENSOR_TYPE=temperature

volumes:
  mysql-data:
